/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useEffect, useLayoutEffect, useRef } from "react";
import { useLoader, useThree } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { draco, TransformControls } from "drei";
import { Object3D } from "three";
import * as THREE from "three";

export function Male(props) {
  // @ts-ignore
  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/models/male.glb",
    draco("/draco-gltf/")
  );

  useEffect(props.onLoad, []);

  return (
    <group name="model" {...props} dispose={null}>
      <group position={[0, 101.72, 2.71]}>
        <primitive object={nodes.Pelvis} />
        <primitive object={nodes.Spine_1} />
      </group>
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.LowerArm_right.geometry}
        skeleton={nodes.LowerArm_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Kneecap_left.geometry}
        skeleton={nodes.Kneecap_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Kneecap_right.geometry}
        skeleton={nodes.Kneecap_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.LowerLeg_left.geometry}
        skeleton={nodes.LowerLeg_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.LowerLeg_right.geometry}
        skeleton={nodes.LowerLeg_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.KneeJoint_left.geometry}
        skeleton={nodes.KneeJoint_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.KneeJoint_right.geometry}
        skeleton={nodes.KneeJoint_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.UpperLeg_right.geometry}
        skeleton={nodes.UpperLeg_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.UpperLeg_left.geometry}
        skeleton={nodes.UpperLeg_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Hip.geometry}
        skeleton={nodes.Hip.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.UpperArm_right.geometry}
        skeleton={nodes.UpperArm_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Neck.geometry}
        skeleton={nodes.Neck.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Head.geometry}
        skeleton={nodes.Head.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Torso.geometry}
        skeleton={nodes.Torso.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.UpperArm_left.geometry}
        skeleton={nodes.UpperArm_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Abdomen.geometry}
        skeleton={nodes.Abdomen.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.LowerArm_left.geometry}
        skeleton={nodes.LowerArm_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Hand_left.geometry}
        skeleton={nodes.Hand_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Toes_Left.geometry}
        skeleton={nodes.Toes_Left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Toes_right.geometry}
        skeleton={nodes.Toes_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Foot_left.geometry}
        skeleton={nodes.Foot_left.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Foot_right.geometry}
        skeleton={nodes.Foot_right.skeleton}
      />
      <skinnedMesh
        material={materials.Default}
        geometry={nodes.Hand_right.geometry}
        skeleton={nodes.Hand_right.skeleton}
      />
    </group>
  );
}
